server:
  port: 8090
  servlet:
    context-path: /demo-es
    application-display-name: demo-es

spring:
  application:
    name: demo-es
  profiles:
    active: local
  data:
    elasticsearch:
      cluster-name: docker-cluster
#      cluster-nodes: 192.168.43.235:9300
      cluster-nodes: 172.17.208.49:9300
      repositories:
        enabled: true
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data



logging:
  config: classpath:logback.xml



