server:
  port: 8090
  servlet:
    context-path: /demo-es
    application-display-name: demo-es

spring:
  application:
    name: demo-es
  profiles:
    active: local, error
  data:
    elasticsearch:
      cluster-name: docker-cluster
#      cluster-nodes: 192.168.43.235:9300
      cluster-nodes: 172.17.208.49:9300
      repositories:
        enabled: true
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data



logging:
  config: classpath:logback-spring.xml

swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: "Spring Boot 测试 ES"
  contact:
    # 维护人
    name: "Klaus Mikaelson"
    email: "niklausjulie@gmail.com"
    url: "https://www.yunlingfly.cn"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "com.klaus.demospringes.api"
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  #  exclude-path: ""
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"
